#include <iostream>
using namespace std;
main(){
       int number1;
       int number2;
       int number3;
       int number4;
       int number5;
       int number6;
       int number7;
       int number8;
       int number9;
       int number10;
       int number11;
       int number12;
       int number13;
       int number14;
       int number15;
       int result1;
       int result2;
       int result3;
       int total;
       cout << "Enter 1st Number: ";
       cin >> number1;
       cout << "Enter 2nd Number: ";
       cin >> number2;
       cout << "Enter 3rd Number: ";
       cin >> number3;
       cout << "Enter 4th Number: ";
       cin >> number4;
       cout << "Enter 5th Number: ";
       cin >> number5;
       cout << "Enter 6th Number: ";
       cin >> number6;
       cout << "Enter 7th Number: ";
       cin >> number7;
       cout << "Enter 8th Number: ";
       cin >> number8;
       cout << "Enter 9th Number: ";
       cin >> number9;
       cout << "Enter 10th Number: ";
       cin >> number10;
       cout << "Enter 11th Number: ";
       cin >> number11;
       cout << "Enter 12th Number: ";
       cin >> number12;
       cout << "Enter 13th Number: ";
       cin >> number13;
       cout << "Enter 14th Number: ";
       cin >> number14;
       cout << "Enter 15th Number: ";
       cin >> number15;
       result1 = number1 + number2 + number3 + number4 + number5;
       result2 = number6 * number7 * number8 * number9 * number10;
       result3 = number11 - number12 - number13 - number14 - number15;
       total = (result1 + result2) - result3;
       cout << "Total: " << total;
}

